[package]
name = "vpn_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.6"
tokio-stream = "0.1"
futures = "0.3"
aes = "0.7"
block-modes = "0.8"
block-padding = "0.2"
hex = "0.4"