[package]
name = "rdapi"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.5"
redis = { version = "0.26.1", features = ["tokio-comp", "connection-manager"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
